// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBackup() {
  return window['go']['main']['DesktopApp']['CreateBackup']();
}

export function DecideConfirmation(arg1) {
  return window['go']['main']['DesktopApp']['DecideConfirmation'](arg1);
}

export function GenerateWorkerToken() {
  return window['go']['main']['DesktopApp']['GenerateWorkerToken']();
}

export function GetModelUsage() {
  return window['go']['main']['DesktopApp']['GetModelUsage']();
}

export function GetRunTrace(arg1) {
  return window['go']['main']['DesktopApp']['GetRunTrace'](arg1);
}

export function GetSecretStatus() {
  return window['go']['main']['DesktopApp']['GetSecretStatus']();
}

export function GetSettings() {
  return window['go']['main']['DesktopApp']['GetSettings']();
}

export function GetSystemHealth() {
  return window['go']['main']['DesktopApp']['GetSystemHealth']();
}

export function ListBackups() {
  return window['go']['main']['DesktopApp']['ListBackups']();
}

export function ListConfirmations() {
  return window['go']['main']['DesktopApp']['ListConfirmations']();
}

export function ListMemories(arg1) {
  return window['go']['main']['DesktopApp']['ListMemories'](arg1);
}

export function ListNodes() {
  return window['go']['main']['DesktopApp']['ListNodes']();
}

export function SaveSecret(arg1) {
  return window['go']['main']['DesktopApp']['SaveSecret'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['DesktopApp']['SendChat'](arg1);
}

export function TestModelConnection() {
  return window['go']['main']['DesktopApp']['TestModelConnection']();
}

export function TestTelegramConnection() {
  return window['go']['main']['DesktopApp']['TestTelegramConnection']();
}

export function UpdateMemory(arg1) {
  return window['go']['main']['DesktopApp']['UpdateMemory'](arg1);
}
