// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRunTrace(arg1:string):Promise<main.DesktopRunTrace>;

export function GetSystemHealth():Promise<main.DesktopSystemHealthResponse>;

export function ListMemories(arg1:main.DesktopMemoryFilter):Promise<main.DesktopMemoryListResponse>;

export function ListNodes():Promise<main.DesktopNodeListResponse>;

export function SendChat(arg1:main.DesktopChatRequest):Promise<main.DesktopChatResponse>;
