// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompleteOnboarding() {
  return window['go']['main']['DesktopApp']['CompleteOnboarding']();
}

export function CreateBackup() {
  return window['go']['main']['DesktopApp']['CreateBackup']();
}

export function DecideConfirmation(arg1) {
  return window['go']['main']['DesktopApp']['DecideConfirmation'](arg1);
}

export function DisableNode(arg1) {
  return window['go']['main']['DesktopApp']['DisableNode'](arg1);
}

export function EnableNode(arg1) {
  return window['go']['main']['DesktopApp']['EnableNode'](arg1);
}

export function ExportDiagnostics() {
  return window['go']['main']['DesktopApp']['ExportDiagnostics']();
}

export function GenerateWorkerToken() {
  return window['go']['main']['DesktopApp']['GenerateWorkerToken']();
}

export function GetModelUsage() {
  return window['go']['main']['DesktopApp']['GetModelUsage']();
}

export function GetOnboardingStatus() {
  return window['go']['main']['DesktopApp']['GetOnboardingStatus']();
}

export function GetRunTrace(arg1) {
  return window['go']['main']['DesktopApp']['GetRunTrace'](arg1);
}

export function GetSecretStatus() {
  return window['go']['main']['DesktopApp']['GetSecretStatus']();
}

export function GetSettings() {
  return window['go']['main']['DesktopApp']['GetSettings']();
}

export function GetSystemHealth() {
  return window['go']['main']['DesktopApp']['GetSystemHealth']();
}

export function ListBackups() {
  return window['go']['main']['DesktopApp']['ListBackups']();
}

export function ListConfirmations() {
  return window['go']['main']['DesktopApp']['ListConfirmations']();
}

export function ListMemories(arg1) {
  return window['go']['main']['DesktopApp']['ListMemories'](arg1);
}

export function ListNodes() {
  return window['go']['main']['DesktopApp']['ListNodes']();
}

export function ListWorkerGatewayAuditLogs() {
  return window['go']['main']['DesktopApp']['ListWorkerGatewayAuditLogs']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['DesktopApp']['RestoreBackup'](arg1);
}

export function SaveModelConfig(arg1) {
  return window['go']['main']['DesktopApp']['SaveModelConfig'](arg1);
}

export function SaveOperationalSettings(arg1) {
  return window['go']['main']['DesktopApp']['SaveOperationalSettings'](arg1);
}

export function SaveSecret(arg1) {
  return window['go']['main']['DesktopApp']['SaveSecret'](arg1);
}

export function SaveTelegramConfig(arg1) {
  return window['go']['main']['DesktopApp']['SaveTelegramConfig'](arg1);
}

export function SendChat(arg1) {
  return window['go']['main']['DesktopApp']['SendChat'](arg1);
}

export function SendTestTelegramMessage(arg1) {
  return window['go']['main']['DesktopApp']['SendTestTelegramMessage'](arg1);
}

export function TestModelConnection() {
  return window['go']['main']['DesktopApp']['TestModelConnection']();
}

export function TestTelegramConnection() {
  return window['go']['main']['DesktopApp']['TestTelegramConnection']();
}

export function UpdateMemory(arg1) {
  return window['go']['main']['DesktopApp']['UpdateMemory'](arg1);
}
