// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetRunTrace(arg1) {
  return window['go']['main']['DesktopApp']['GetRunTrace'](arg1);
}

export function GetSystemHealth() {
  return window['go']['main']['DesktopApp']['GetSystemHealth']();
}

export function ListMemories(arg1) {
  return window['go']['main']['DesktopApp']['ListMemories'](arg1);
}

export function ListNodes() {
  return window['go']['main']['DesktopApp']['ListNodes']();
}

export function SendChat(arg1) {
  return window['go']['main']['DesktopApp']['SendChat'](arg1);
}
